active=no
admin_run_as=diradmin
admin_widgets=
author=SSI Group ApS
id=cloudflare_sync
installed=no
menu_admin=
menu_reseller=
menu_user=
name=Cloudflare Sync
reseller_run_as=
reseller_widgets=
timeout=
user_run_as=
user_widgets=
version=0.1
version_url=https://raw.githubusercontent.com/boutzamat/directadmin-cloudflare/master/version.txt
update_url=https://github.com/boutzamat/directadmin-cloudflare/releases/latest/download/cloudflare_sync.tar.gz
